# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("LogIN Page")
        MainWindow.resize(480, 640)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("color: rgb(46, 52, 54);\n"
"background-color: rgb(114, 159, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogIN = QtWidgets.QPushButton(self.centralwidget)
        self.LogIN.setGeometry(QtCore.QRect(60, 300, 151, 111))
        self.LogIN.setMinimumSize(QtCore.QSize(151, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LogIN.setFont(font)
        self.LogIN.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"border-radius:30px\n"
"")
        self.LogIN.setObjectName("LogIN")
        self.Password = QtWidgets.QLabel(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(60, 230, 341, 31))
        self.Password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 11pt \"Ubuntu Mono\";")
        self.Password.setObjectName("Password")
        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(60, 170, 341, 31))
        self.Username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 11pt \"Ubuntu Mono\";")
        self.Username.setObjectName("Username")
        self.Sign_Up = QtWidgets.QPushButton(self.centralwidget)
        self.Sign_Up.setGeometry(QtCore.QRect(270, 300, 151, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Sign_Up.setFont(font)
        self.Sign_Up.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"border-radius:30px\n"
"")
        self.Sign_Up.setObjectName("Sign_Up")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 70, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.label.setObjectName("label")
#
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LogIN.setText(_translate("MainWindow", "Log In"))
        self.Password.setText(_translate("MainWindow", "Enter Your Password"))
        self.Username.setText(_translate("MainWindow", "Enter Your Username"))
        self.Sign_Up.setText(_translate("MainWindow", "Sign Up"))
        self.label.setText(_translate("MainWindow", " Log In Page"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QWidget()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())












